### ISSUE TITLE
randomStrings appears not to cope with first parameter having value 0

### ISSUE THREAD

**Issue by russel** [renatoathaydes/specks#13]
I am using randomStrings to create a number of random strings.

I am calling randomStrings(i, 1, 8) where i is non-negative. If i has the value zero I appear to get a "Count must be positive" exception, if i is non-zero and positive things work as expected.

PS is there an easy way of constraining the character set that randomStings creates strings from?

**Comment by renatoathaydes** [comment]
If you don't give a positive count, no string will be generated and no test will run, which is probably never what you want.

The full parameter list of `randomStrings` is:

``` ceylon
Integer count = 100, Integer shortest = 0, Integer longest = 100, [Character+] allowedChars = '\{#20}'..'\{#7E}', Random random = defaultRandom
```

So, the fourth parameter lets you restrict the characters that can be used. You could call it like this, for example:

``` ceylon
value strings = randomStrings(100, 1, 20, 'a'..'z');
```

**Comment by russel** [comment]
Sadly I actually want 'A'..'Z' + 'a'..'z' + '-' but ranges are not summable :-(

**Comment by russel** [comment]
I am trying to generate sets of strings, one of the test cases is a set with no entries, so yes no string is one of the cases I want.

**Comment by renatoathaydes** [comment]
If we fix `randomStrings()` to possibly return a 0-length array, I'll have to change the return type from `[Character+]` to `[Character*]`, in which case the result cannot be used in test examples (which must have at least one example). So I suggest you create your own function which uses `randomString()` if `count > 0`, otherwise return an empty one.
