### ISSUE TITLE
`expectToThrow` not working as documented

### ISSUE THREAD

**Issue by dlkw** [renatoathaydes/specks#16]
On the Java backend, the example from the Readme.md
```ceylon
errorCheck {
    description = "Dividing 1 by 0 results in an Exception";
    function when() => 1 / 0;
    expectToThrow(`Exception`)
}
```
does not work, because (as of now), the exception thrown is a `java.lang.ArithmeticException`, but `expectToThrow` checks for exact match.

It is a bit doubtful that a ceylon language feature like the division should throw a backend dependent runtime exception, but that may even be legitimate. The JS backend throws a plain `ceylon.language.Exception`, so it might be worthwhile reporting to Ceylon a missing Exception type for this situation.

However, for some situations I think it'd be a good idea to have a predefined specks assertion that accepts also the given exception's (no, better `Throwable`, see #11) subtypes. What do you think?

**Comment by renatoathaydes** [comment]
I believe Ceylon has always thrown platform Exceptions in cases like this, where the actual operation is a primitive operation, hence implemented at platform level. I think specks works correctly in this case because Java's `ArithmeticException` is not a subtype of `Exception`. I have to check the source, but I expected that any subtype of the type you give to `expectToThrow` being thrown should pass the test. IF that's not the case, I will change that.

**Comment by renatoathaydes** [comment]
I've actually added a test for the example case and it now works.

https://github.com/renatoathaydes/specks/blob/e3d70c459b921e63425ef16b0a6b717c6fbadf4f/tests/test/com/athaydes/specks/specksTests.ceylon#L110
